### ISSUE TITLE
$400 a month?

### ISSUE THREAD

**Issue by kemp** [14ercooper/ctm_repository#2]
Who's your hosting provider? That seems like a lot :laughing:

**Comment by 14ercooper** [comment]
(ignoring that this isn't actually an issue and more of just a question)
It's actually a lot cheaper than a lot of people seem to think, especially given what I'm working with here - several people have made comments along the lines of "I could run it cheaper", at least until they got some semblance of the scope the repo actually operates at.
Some actual numbers (looking at the metrics from the last 30 days) - 1.49 million requests to the ctmrepository.com domain, containing a total of 24.4TB of data. These requests were made by ~51.2k unique visitors (using standard methods of counting unique visitors). The traffic isn't evenly spread out, either, with major spikes on Fridays (auto-scaling helps, but you still have to be able to handle around half the traffic hitting the site during around 10% of the month). All this has to happen without causing major latency for loading the site, since SEO and similar heavily penalizes you if your site is slow. If you can beat my pricing (most recent billing period totalled to $417.33), feel free to let me know!
I also don't have a single "hosting provider" (though a good chunk of the hosting does fall under OVH), because I've put quite a bit of effort into cost optimization, which means that some parts of the stack come from other providers who do that part better and cheaper.

**Comment by kemp** [comment]
@14ercooper, thank you for taking the time to professionally respond to my comment. I appreciate that. 

I also appreciate you being transparent with your costs for running ctmrepository.com

I imagine most of your cost and load is for the map downloads. You may have luck using Cloudflare R2 for your storage instead, the main reason being they don’t charge for egress traffic.  They have a calculator available here: https://r2-calculator.cloudflare.com/

Another benefit of using a third-party like this for storage is the download could take place directly from their servers, reducing total load on your server. 

I’d gladly help if that’s something you’d be interested in. I’m thankful for the work you do to provide free services for the Minecraft community!
